### ISSUE TITLE
Phase II missions not appearing

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#10]
Reported by Luwen as a comment in issue #1 for instructor:

actually, spawned phase II missions don't show up anymore on student view. Try:

create a new mission on Instructor
take that new mission on Student
go back to Instructor and spawn Phase II
---> the spawned mission doesn't show up on Student.

**Comment by luwen-huang** [comment]
is this related to #41? all phase II missions are showing up properly for me now...

**Comment by coleshaw** [comment]
Grr, so I can verify that now phase ii missions show up for me….
