### ISSUE TITLE
Target indicator not correct

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#27]
Chad completed the scaffold in a target (Wrong, Wrong, Right) with only one scaffold deep, but the target indicator shows red instead of "tried". For third directive, was Wrong / Right, and it shows "tried".  Directive "Find the center and radius of a circle".

Dipa has the same issue and can replicate Solve linear inequalities and state the solution in interval notation.

**Comment by luwen-huang** [comment]
fixed. was a bug in the selectors. i now have a test for it.
