### ISSUE TITLE
No green checkmark next to the right choice

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#35]
Reported by Dipa, screenshot below

![photo](https://cloud.githubusercontent.com/assets/4930129/21909454/0c4dc3a4-d8e6-11e6-9c37-ca653080e1ef.JPG)

**Comment by coleshaw** [comment]
Same problem in the same directive, but got question wrong -- no red X. Is it something to do with width of the text?

**Comment by coleshaw** [comment]
Most likely this is CSS -- seems like the words overflow the choice box (see how the text overruns the gray background text), so the X and check most likely are hidden by the text....

**Comment by luwen-huang** [comment]
i've increased the size of the question card. should be fixed now.
