### ISSUE TITLE
Directive count doesn't update?

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#40]
When I answer questions, the new directive count (---/3) doesn't update?

![captura de pantalla 2017-01-17 a las 9 35 09 am](https://cloud.githubusercontent.com/assets/4930129/22024553/5a9a2fc4-dc98-11e6-949c-8227ccb7ccc6.png)

**Comment by luwen-huang** [comment]
It's not supposed to update until you navigate the route.

Luwen

**Comment by coleshaw** [comment]
Ah, okay, I was expecting it to change as soon as I answered the target…

**Comment by luwen-huang** [comment]
so, the point of this was to urge the students to really navigate through and let them see which ones have been 'really' completed. if we have it change as soon as you answer, then people wouldn't know which ones are actually completed vs. just answered...

**Comment by coleshaw** [comment]
Ah, I see, okay. Thanks for clarifying. Might be good to include in documentation or tutorial mission...
