### ISSUE TITLE
Phase II missions not showing up client-side

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#41]
They come in from the middleman:

https://gist.github.com/cjshawMIT/2d6813afe007b6c799f17d9346b6d519

But not showing up in the UI:

![captura de pantalla 2017-01-17 a las 4 14 53 pm](https://cloud.githubusercontent.com/assets/4930129/22040218/1e091146-dcd0-11e6-80e3-689bdd54c3cd.png)

To replicate (as visitor):
- Create a mission in the instructor app
- Log in to the student app as visitor, different ID
- Try the mission
- Go back to the instructor app, re-click on the mission (to update results)
- Launch phase ii
- Go back to the student app and click on `Missions` in the breadcrumbs
- Nothing changes in the UI, but you can see the call in the Network tab shows the phase ii mission...

**Comment by coleshaw** [comment]
@luwen-huang , do you think this is because of some weird interaction with the localStorage library we're using?

**Comment by luwen-huang** [comment]
umm...i followed your instructions exactly and couldn't replicate it with visitor or d2l-callback. can you pull and install common, and verify?

**Comment by coleshaw** [comment]
agree, can't verify. Ugh.
