### ISSUE TITLE
Can submit on a closed mission

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#43]
D2L callback, S99999991, try College Algebra Unit 1. The mission closed on 1-14, but the `Submit` button still shows up.

![captura de pantalla 2017-01-24 a las 10 32 59 am](https://cloud.githubusercontent.com/assets/4930129/22253675/7fb420d4-e220-11e6-9373-748b216953c4.png)

**Comment by luwen-huang** [comment]
should be fixed now. install new common.
