### ISSUE TITLE
Next deadline is not accurate -- missions are not returned sorted chronologically

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#50]
In `src/routes/Home/components/Home.js`, this is used to show the next deadline:

```
moment(this.props.missions[0].deadline).format('dddd[,] MMMM D')
```

But the `getMissions` reducer does not sort the missions chronologically, and the server doesn't either...so we shouldn't just take the first index.

**Comment by luwen-huang** [comment]
fixed. we can't do this now in any case since the student needs to select their course first.
