### ISSUE TITLE
CloudFront parsing for images is not working

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#6]
![captura de pantalla 2016-12-13 a las 3 33 08 pm](https://cloud.githubusercontent.com/assets/4930129/21157994/80cb456c-c149-11e6-9b79-94851f3daa24.png)

**Comment by coleshaw** [comment]
Why yes, we need to use `axios` to support FF, Safari, and Safari Mobile (the three browsers that failed today during our call with ACC):

export function convertImagePaths (itemObject) {
  // TODO: refactor with axios?

**Comment by coleshaw** [comment]
Okay, in reality we need a middleman URL for this, because `qbankFetch` is being called, but it's not declared / used anywhere in the student app / common

**Comment by luwen-huang** [comment]
Re-opening the problem where submit answer doesn't work when it's a choice with an image:

a POST to `https://fbw-web-backend.herokuapp.com/middleman/banks/assessment.Bank%3A585a939c71e4828a46da073f%40bazzim.MIT.EDU/takens/assessment.AssessmentSection%3A585a93a471e4828a46da0753%40bazzim.MIT.EDU/questions/assessment.Item%3A585a93ab71e4828a46da0777%40assessment-session/submit` gives a 500

<img width="1404" alt="screen shot 2016-12-21 at 7 41 05 am" src="https://cloud.githubusercontent.com/assets/2822290/21393251/de55f3dc-c750-11e6-9512-0611dc0e7908.png">

<img width="1396" alt="screen shot 2016-12-21 at 7 40 46 am" src="https://cloud.githubusercontent.com/assets/2822290/21393235/d00cdb74-c750-11e6-8044-bd126e9727b2.png">
