### ISSUE TITLE
submitResponse sometimes doesn't work

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student#9]
I can't consistently replicate it, but i know `submitResponse` sometimes fail. Hoping that the middleman tests will pinpoint the bug.

**Comment by coleshaw** [comment]
Did you pull latest platform-common? I fixed a bug when the solution had a image in it, that would make submitResponse appear to not work. And can you define “not work” — when you refreshed, was the answer submitted?
